### PR TITLE
Hvn/image comparison

### PR DESCRIPTION
**Pull request by hungngo97**
#90 Change Jest to compare image snapshots instead of SVG

### CODE REVIEW

**Comment by hungngo97** [comment]
This is my initial attempt on using [jest-image-snapshot](https://github.com/americanexpress/jest-image-snapshot) but somehow it doesn't pass on Github actions yet. I tried to create snapshots from both my Macbook Pro as well as Docker Container dev on VSCode to generate images like how I did last time. 
But the images generated by Github actions is different and even some of the images the size is even different. Did you have this problem while testing Vega? 
Example: 
```    
Expected image to be the same size as the snapshot (326x247), but was different (341x247).
```
@domoritz

**Comment by domoritz** [comment]
Yeah, images can be different due to differences in fonts. Can you accept more difference?

**Comment by hungngo97** [comment]
We can definitely crank up the threshold but if the size are different from the beginning, jest already rejects the comparison

**Comment by domoritz** [comment]
Hmm, I don't think there is a way to produce the same image size. Could we resize the images? Or is there an option to skip the size comparison check?

**Comment by hungngo97** [comment]
We cannot skip the size check as far as I know but I think we can resize image with extra dependency. Though maybe the pixel after resize will not be an exact match to the expected image so maybe I need an increase on the comparison threshold.

**Comment by domoritz** [comment]
Hmm, doesn't feel great but hopefully that makes our test pass at least.

**Comment by domoritz** [comment]
Do you have time to finish this pull request?

**Pull request closed without merging**
